import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Wi-Pi Touch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>

          <h1>Wi-Pi Touch</h1>
        </header>
        {children}
        <footer>
          &copy; Jake Kim
        </footer>
      </body>
    </html>
  );
}
